name: Azure Pipelines
variables:
  python.version: "3.7.6"

stages:
  - stage: Build
    jobs:
      - job: build_artifacts
        displayName: BuildArtifacts
        pool: 
          vmImage: ubuntu-latest
        variables: 
          myPubKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC1A1wSSJHY6uqogNJd+T1m+B9q14QJAy1Pj+HZ3wJ41lbMavEwzX/quexa+X6niENryG3x/Ba9gk64DgAh/mE/6ZknExv/z6sUw4UAkuaRuFCSs9b2xehBMgQxg7ojnz5JDrdoeDYNrEmU2cvKDZy0XdgQXbeyt89pFk7c6UdHuVnK+UtTLeu2NRsQowgSLbblrlcNtEioCDmUg49jTfwpZaD74K+jaaVZO1v8DGbfgQfHej9XNEXHK5sQ1mfz3dYxq+2LgCxdhIpLMWriGCPtzAfpzhi7F6pBiI2WxfG5T8Q8s9nLeZEdv0WdLqTFWIxUnc7jCLyfgzh6Zm6E45tt akwari@akwari-Dell-System-XPS-L502X'
          hostEntry: 'SHA256:AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl'
        steps:
          #Needed for Terraform VM deployment
          - task: InstallSSHKey@0
            inputs:
              knownHostsEntry: $(hostEntry)
              sshPublicKey: '$(myPubkey)'
              sshKeySecureFile: 'id_rsa'
              
          - task: ArchiveFiles@2
            displayName: ArchiveFakeRestAPI
            inputs:
              rootFolderOrFile: '$(System.DefaultWorkingDirectory)/automatedtesting/jmeter/fakerestapi'
              includeRootFolder: false
              archiveType: "zip"
              archiveFile: "$(Build.ArtifactStagingDirectory)/$(Build.BuildId)-fakerestapi.zip"
          - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId)-fakerestapi.zip
            displayName: "Upload Package"
            artifact: drop-fakerestapi
  - stage: Deploy
    jobs:
      - deployment: deploy_fakeRestAPI
        displayName: DeployFakeRestAPI
        pool: 
          vmImage: ubuntu-latest
        environment: 'TEST'
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureWebApp@1
                  displayName: "DeployAzureWebApp"
                  inputs:
                    azureSubscription: 'quality-app'
                    appName: 'saasApp3-AppService'
                    appType: webApp
                    package: $(Pipeline.Workspace)/drop-fakerestapi/$(Build.BuildId)-fakerestapi.zip
      - deployment: deploy_to_vm
        displayName: DeployAppToVM
        environment:
          name:  'TEST'
          resourceType: VirtualMachine
          tags: project-3
        strategy:
          runOnce:
            deploy:
              steps:
              - task: Bash@3
                inputs:
                  targetType: 'inline'
                  script: |
                    #! /bin/bash

                    sudo apt-get upgrade -y
                    sudo apt-get install python3-pip -y
                    sudo apt-get install unzip -y
                    sudo apt-get install -y chromium-browser
                    pip3 install selenium
                    export PATH=$PATH:home/akwari
